---
# tasks file for roles/python

  - name: source installation
    include: install_from_sources.yml
    when: python_from_sources

  - name: update python version
    include: install_from_ppa.yml
    when: python_from_ppa

  - name: verify python version
    shell: python --version 2>&1 | grep {{ python_version }}
    changed_when: false
